# docker image settings, required section
container:
  # Image name to start on worker, required param.
  image: sonm/clm-eth-pasc-opencl:latest
  # Env variables that will be passed to container on start.
  env:
    ETH_POOL: <pool>
    ETH_ADDR: <addr>
    ETH_WORKER: <worker>
    ETH_EMAIL: <email>
    PASC_POOL: <pool>
    PASC_ADDR: <addr>
    PASC_WORKER: <worker>
    PASC_EMAIL: <email>
