# docker image settings, required section
container:
  # Image name to start on worker, required param.
  image: sonm/monero-amd:latest
  # Env variables that will be passed to container on start.
  env:
    WALLET: <wallet>
    # optional params
    # WORKER: sonm_worker
    # POOL: xmr-eu1.nanopool.org:14444
